<?php
require_once __DIR__ . '/config/session.php';
require_once __DIR__ . '/config/functions.php';
require_once __DIR__ . '/config/csrf.php';
require_login();
if ($_SERVER['REQUEST_METHOD'] !== 'POST') abort_request(405, 'คำขอไม่ถูกต้อง');
csrf_verify();
$conn = getDbConnection();
$commentId = input_id($_POST, 'comment_id');
$stmt = $conn->prepare('SELECT user_id, note_id FROM comments WHERE comment_id = ?');
$stmt->bind_param('i', $commentId); $stmt->execute();
$comment = $stmt->get_result()->fetch_assoc(); $stmt->close();
if (!$comment) abort_request(404, 'ไม่พบความคิดเห็น');
if ((int)$comment['user_id'] !== (int)$_SESSION['user_id'] && !is_admin()) abort_request(403, 'คุณไม่มีสิทธิ์ลบความคิดเห็นนี้');
$conn->begin_transaction();
$del = $conn->prepare('DELETE FROM comments WHERE comment_id = ?');
$del->bind_param('i', $commentId); $del->execute(); $del->close();
log_security_event($conn, $_SESSION['user_id'], $_SESSION['username'], 'COMMENT_DELETE', "ลบคอมเมนต์ comment_id={$commentId}");
$conn->commit(); $conn->close();
header('Location: note_detail.php?id=' . (int)$comment['note_id'] . '#comments'); exit;
