import { Check, Database, KeyRound, Play, ShieldCheck, ArrowUpRight } from 'lucide-react';

export function SetupGuide() {
  return <><section className="hero setup-hero"><div><div className="eyebrow">A new chapter for NoteShare</div><h1>พื้นที่แบ่งปันเดิม<br/><span>พร้อมเริ่มต้นบน Supabase</span></h1><p>เว็บเวอร์ชัน Next.js พร้อมแล้ว เชื่อมโปรเจกต์ Supabase ของคุณเพื่อเริ่มสมัครสมาชิก แบ่งปันชีท และดาวน์โหลดได้จากทุกที่</p><a className="btn" href="https://supabase.com/dashboard" target="_blank" rel="noreferrer">สร้างโปรเจกต์ Supabase<ArrowUpRight className="icon"/></a></div><div className="setup-status"><Database size={44}/><h2>เชื่อมต่อครั้งเดียว<br/>เริ่มแบ่งปันได้เลย</h2><span><Check className="icon"/>ไม่ต้องติดตั้ง MySQL</span><span><Check className="icon"/>เปิดเว็บด้วย npm run dev</span><span><ShieldCheck className="icon"/>ฐานข้อมูลและไฟล์ส่วนตัว</span></div></section>
    <div className="section-heading"><div><h2>ตั้งค่าเพียง 3 ขั้นตอน</h2><p>ยังไม่มีข้อมูลตัวอย่างหรือบัญชีสมมติในฐานข้อมูลของคุณ</p></div><span className="count-label">เริ่มต้นใช้งาน</span></div>
    <div className="setup-grid"><article className="card"><Database className="icon"/><div className="eyebrow">01 / Database</div><h3>สร้างโปรเจกต์และตาราง</h3><p>สร้างโปรเจกต์ใน Supabase แล้วเปิด SQL Editor วางเนื้อหาจากไฟล์นี้และกด Run</p><code>supabase/migrations/<br/>202610080001_noteshare.sql</code><p className="note-meta">สคริปต์นี้ใช้กับโปรเจกต์ใหม่ และสร้างตารางพร้อมสิทธิ์การเข้าถึงให้ครบ</p></article>
      <article className="card"><KeyRound className="icon"/><div className="eyebrow">02 / Connect</div><h3>ใส่คีย์ในเครื่องของคุณ</h3><p>คัดลอก <code>.env.example</code> เป็น <code>.env.local</code> แล้วใส่ Project URL, Publishable Key และ Secret Key จาก Supabase</p><p>สร้าง APP_SESSION_SECRET ด้วยคำสั่งในคู่มือ <code>SUPABASE_SETUP.md</code></p><p className="note-meta">Secret Key เก็บไว้ในเครื่องและเซิร์ฟเวอร์เท่านั้น</p></article>
      <article className="card"><Play className="icon"/><div className="eyebrow">03 / Launch</div><h3>เปิดเว็บ แล้วสมัครสมาชิก</h3><p>ตั้ง Auth Site URL เป็น <code>http://localhost:3000</code> เพิ่ม Redirect URL ตามคู่มือ จากนั้นเปิดเว็บใหม่</p><pre><code>npm run dev</code></pre><p className="note-meta">เข้าสู่ระบบด้วยอีเมลและรหัสผ่านที่สมัครในเวอร์ชันนี้</p></article></div>
    <aside className="help-card"><h3>คู่มือพร้อมใช้ในโปรเจกต์</h3><p>เปิด <strong>SUPABASE_SETUP.md</strong> สำหรับขั้นตอนละเอียดและการตั้ง Admin คนแรก โค้ดและข้อมูล PHP/MySQL เดิมเก็บไว้สำหรับอ้างอิง โดยยังไม่ได้ย้ายข้อมูลเข้า Supabase</p></aside>
  </>;
}
