-- Run once in the SQL Editor of a NEW Supabase project.
-- Passwords belong to Supabase Auth, not to public.profiles.
begin;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to anon, authenticated, service_role;

create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username varchar(50) not null unique check (username ~ '^[A-Za-z0-9_]{4,50}$'),
  email varchar(100) not null unique,
  full_name varchar(100) not null check (char_length(trim(full_name)) between 1 and 100),
  role text not null default 'user' check (role in ('user','admin')),
  status text not null default 'active' check (status in ('active','suspended')),
  created_at timestamptz not null default now()
);
create table public.subjects (
  subject_id integer generated by default as identity primary key,
  subject_name varchar(150) not null unique check (char_length(trim(subject_name)) between 1 and 150),
  created_at timestamptz not null default now()
);
create table public.notes (
  note_id integer generated by default as identity primary key,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  subject_id integer not null references public.subjects(subject_id) on delete restrict,
  title varchar(200) not null check (char_length(trim(title)) between 1 and 200),
  description text not null default '' check (char_length(description) <= 2000),
  object_path text not null unique,
  original_file_name varchar(255) not null,
  file_size integer not null check (file_size between 1 and 10485760),
  file_type text not null check (file_type in ('pdf','doc','docx','ppt','pptx','jpg','jpeg','png')),
  mime_type text not null,
  download_count integer not null default 0 check (download_count >= 0),
  status text not null default 'active' check (status in ('active','removed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.comments (
  comment_id integer generated by default as identity primary key,
  note_id integer not null references public.notes(note_id) on delete cascade,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  content text not null check (char_length(trim(content)) between 1 and 1000),
  created_at timestamptz not null default now()
);
create table public.download_logs (
  log_id bigint generated by default as identity primary key,
  note_id integer not null references public.notes(note_id) on delete cascade,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  downloaded_at timestamptz not null default now()
);
create table public.security_logs (
  log_id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(user_id) on delete set null,
  username_attempt varchar(100),
  action varchar(50) not null,
  detail varchar(255) not null default '',
  ip_address inet,
  created_at timestamptz not null default now()
);
create index notes_user_idx on public.notes(user_id);
create index notes_subject_idx on public.notes(subject_id);
create index notes_recent_idx on public.notes(status, created_at desc, note_id desc);
create index comments_note_idx on public.comments(note_id);
create index download_logs_user_idx on public.download_logs(user_id);
create index download_logs_note_idx on public.download_logs(note_id);
create index security_login_email_idx on public.security_logs(action, username_attempt, created_at);
create index security_login_ip_idx on public.security_logs(action, ip_address, created_at);

create function private.is_active() returns boolean language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.profiles where user_id = auth.uid() and status = 'active');
$$;
create function private.is_admin() returns boolean language sql stable security definer set search_path = '' as $$
  select exists(select 1 from public.profiles where user_id = auth.uid() and status = 'active' and role = 'admin');
$$;
create function private.require_active() returns uuid language plpgsql security definer set search_path = '' as $$
begin
  if not private.is_active() then raise exception 'Authentication required' using errcode = '42501'; end if;
  return auth.uid();
end; $$;
create function private.audit(p_action text, p_detail text default '') returns void language sql security definer set search_path = '' as $$
  insert into public.security_logs(user_id, username_attempt, action, detail)
  select auth.uid(), (select username from public.profiles where user_id = auth.uid()), p_action, left(p_detail,255);
$$;

alter table public.profiles enable row level security;
alter table public.subjects enable row level security;
alter table public.notes enable row level security;
alter table public.comments enable row level security;
alter table public.download_logs enable row level security;
alter table public.security_logs enable row level security;

-- Revoke project defaults: clients never get unrestricted table writes.
revoke all on public.profiles, public.subjects, public.notes, public.comments, public.download_logs, public.security_logs from anon, authenticated;
grant select(user_id, username, full_name) on public.profiles to anon;
grant select(user_id, username, full_name, role, status, created_at) on public.profiles to authenticated;
grant select on public.subjects, public.notes, public.comments to anon, authenticated;
grant select on public.download_logs, public.security_logs to authenticated;
grant all on public.profiles, public.subjects, public.notes, public.comments, public.download_logs, public.security_logs to service_role;
grant usage, select on all sequences in schema public to service_role;

create policy profiles_read on public.profiles for select to anon, authenticated using (true);
create policy subjects_read on public.subjects for select to anon, authenticated using (true);
create policy notes_read on public.notes for select to anon, authenticated
  using (status = 'active' or (private.is_active() and (user_id = auth.uid() or private.is_admin())));
create policy comments_read on public.comments for select to anon, authenticated
  using (exists(select 1 from public.notes n where n.note_id = comments.note_id and n.status = 'active'));
create policy downloads_read on public.download_logs for select to authenticated
  using (private.is_active() and (user_id = auth.uid() or private.is_admin()));
create policy security_read on public.security_logs for select to authenticated using (private.is_admin());

create view public.note_catalog with (security_invoker = true) as
select n.*, p.username, p.full_name, s.subject_name
from public.notes n join public.profiles p on p.user_id = n.user_id
join public.subjects s on s.subject_id = n.subject_id;
grant select on public.note_catalog to anon, authenticated, service_role;

create function private.new_auth_user() returns trigger language plpgsql security definer set search_path = '' as $$
declare uname text; fname text;
begin
  uname := coalesce(nullif(new.raw_user_meta_data->>'username',''), 'user_' || left(replace(new.id::text,'-',''),12));
  fname := coalesce(nullif(trim(new.raw_user_meta_data->>'full_name'),''), uname);
  insert into public.profiles(user_id, username, email, full_name)
    values(new.id, uname, lower(new.email), fname);
  -- Never copy role/status from untrusted signup metadata.
  insert into public.security_logs(user_id,username_attempt,action,detail)
    values(new.id,uname,'REGISTER','สมัครสมาชิกผ่าน Supabase Auth');
  return new;
end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function private.new_auth_user();

create function public.search_notes(p_query text default '', p_subject integer default null, p_page integer default 1)
returns setof public.note_catalog language sql stable security invoker set search_path = '' as $$
  select * from public.note_catalog n
  where n.status = 'active' and (p_subject is null or n.subject_id = p_subject)
    and char_length(p_query) <= 100
    and (trim(p_query) = '' or position(lower(trim(p_query)) in lower(n.title || ' ' || n.description || ' ' || n.subject_name)) > 0)
  order by n.created_at desc,n.note_id desc
  limit 12 offset (greatest(1,least(p_page,100000))-1)*12;
$$;
create function public.search_notes_count(p_query text default '', p_subject integer default null)
returns integer language sql stable security invoker set search_path = '' as $$
  select count(*)::integer from public.note_catalog n
  where n.status = 'active' and (p_subject is null or n.subject_id = p_subject)
    and char_length(p_query) <= 100
    and (trim(p_query) = '' or position(lower(trim(p_query)) in lower(n.title || ' ' || n.description || ' ' || n.subject_name)) > 0);
$$;

create function public.create_note(p_title text, p_description text, p_subject text, p_object_path text,
  p_original_name text, p_size integer, p_type text, p_mime text)
returns integer language plpgsql security definer set search_path = '' as $$
declare actor uuid; sid integer; nid integer;
begin
  actor := private.require_active();
  if char_length(trim(p_title)) not between 1 and 200 or char_length(p_description) > 2000
     or char_length(trim(p_subject)) not between 1 and 150 then raise exception 'Invalid note'; end if;
  if split_part(p_object_path,'/',1) <> actor::text
     or right(p_object_path,char_length(p_type)+1) <> '.' || p_type
     or not exists(select 1 from storage.objects where bucket_id = 'notes' and name = p_object_path
       and metadata->>'size' = p_size::text and metadata->>'mimetype' = p_mime)
     then raise exception 'Invalid file ownership' using errcode = '42501'; end if;
  insert into public.subjects(subject_name) values(trim(p_subject)) on conflict(subject_name) do nothing;
  select subject_id into sid from public.subjects where subject_name = trim(p_subject);
  insert into public.notes(user_id,subject_id,title,description,object_path,original_file_name,file_size,file_type,mime_type)
    values(actor,sid,trim(p_title),p_description,p_object_path,p_original_name,p_size,p_type,p_mime) returning note_id into nid;
  perform private.audit('NOTE_CREATE','note_id=' || nid);
  perform private.audit('FILE_UPLOAD','note_id=' || nid);
  return nid;
end; $$;
create function public.update_note(p_note_id integer, p_title text, p_description text, p_subject text)
returns void language plpgsql security definer set search_path = '' as $$
declare actor uuid; owner_id uuid; sid integer;
begin
  actor := private.require_active();
  select user_id into owner_id from public.notes where note_id=p_note_id and status='active' for update;
  if not found then raise exception 'Note not found' using errcode='P0002'; end if;
  if owner_id <> actor and not private.is_admin() then raise exception 'Forbidden' using errcode='42501'; end if;
  if char_length(trim(p_title)) not between 1 and 200 or char_length(p_description)>2000
     or char_length(trim(p_subject)) not between 1 and 150 then raise exception 'Invalid note'; end if;
  insert into public.subjects(subject_name) values(trim(p_subject)) on conflict(subject_name) do nothing;
  select subject_id into sid from public.subjects where subject_name=trim(p_subject);
  update public.notes set title=trim(p_title),description=p_description,subject_id=sid,updated_at=now() where note_id=p_note_id;
  perform private.audit('NOTE_UPDATE','note_id=' || p_note_id);
end; $$;
create function public.remove_note(p_note_id integer) returns void language plpgsql security definer set search_path = '' as $$
declare actor uuid; owner_id uuid;
begin
  actor := private.require_active();
  select user_id into owner_id from public.notes where note_id=p_note_id and status='active' for update;
  if not found then raise exception 'Note not found' using errcode='P0002'; end if;
  if owner_id <> actor and not private.is_admin() then raise exception 'Forbidden' using errcode='42501'; end if;
  update public.notes set status='removed',updated_at=now() where note_id=p_note_id;
  perform private.audit('NOTE_DELETE','note_id=' || p_note_id);
end; $$;
create function public.add_comment(p_note_id integer,p_content text) returns void language plpgsql security definer set search_path = '' as $$
declare actor uuid; cid integer;
begin
  actor := private.require_active();
  -- Lock the parent to serialize against concurrent removal.
  perform 1 from public.notes where note_id=p_note_id and status='active' for share;
  if not found then raise exception 'Note not found' using errcode='P0002'; end if;
  insert into public.comments(note_id,user_id,content) values(p_note_id,actor,trim(p_content)) returning comment_id into cid;
  perform private.audit('COMMENT_CREATE','comment_id=' || cid);
end; $$;
create function public.remove_comment(p_comment_id integer) returns void language plpgsql security definer set search_path = '' as $$
declare actor uuid; owner_id uuid;
begin
  actor := private.require_active();
  select user_id into owner_id from public.comments where comment_id=p_comment_id for update;
  if not found then raise exception 'Comment not found' using errcode='P0002'; end if;
  if owner_id <> actor and not private.is_admin() then raise exception 'Forbidden' using errcode='42501'; end if;
  delete from public.comments where comment_id=p_comment_id;
  perform private.audit('COMMENT_DELETE','comment_id=' || p_comment_id);
end; $$;
create function public.record_download(p_note_id integer) returns void language plpgsql security definer set search_path = '' as $$
declare actor uuid;
begin
  actor := private.require_active();
  update public.notes set download_count=download_count+1 where note_id=p_note_id and status='active';
  if not found then raise exception 'Note not found' using errcode='P0002'; end if;
  insert into public.download_logs(note_id,user_id) values(p_note_id,actor);
  perform private.audit('FILE_DOWNLOAD','note_id=' || p_note_id);
end; $$;
create function public.set_user_status(p_user_id uuid,p_status text) returns void language plpgsql security definer set search_path = '' as $$
begin
  if not private.is_admin() or p_user_id=auth.uid() then raise exception 'Forbidden' using errcode='42501'; end if;
  if p_status not in ('active','suspended') then raise exception 'Invalid status'; end if;
  update public.profiles set status=p_status where user_id=p_user_id;
  if not found then raise exception 'User not found' using errcode='P0002'; end if;
  perform private.audit('ADMIN_USER_STATUS_CHANGE','user_id=' || p_user_id || ' -> ' || p_status);
end; $$;
create function public.admin_users() returns table(user_id uuid,username varchar,full_name varchar,email varchar,role text,status text,created_at timestamptz)
language plpgsql stable security definer set search_path = '' as $$
begin
  if not private.is_admin() then raise exception 'Forbidden' using errcode='42501'; end if;
  return query select p.user_id,p.username,p.full_name,p.email,p.role,p.status,p.created_at from public.profiles p order by p.created_at desc;
end; $$;
create function public.my_stats() returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare actor uuid;
begin
  actor := private.require_active();
  return jsonb_build_object(
    'total',(select count(*) from public.notes where user_id=actor),
    'active',(select count(*) from public.notes where user_id=actor and status='active'),
    'downloads',(select coalesce(sum(download_count),0) from public.notes where user_id=actor),
    'comments',(select count(*) from public.comments c join public.notes n using(note_id) where n.user_id=actor));
end; $$;
create function public.admin_stats() returns jsonb language plpgsql stable security definer set search_path = '' as $$
begin
  if not private.is_admin() then raise exception 'Forbidden' using errcode='42501'; end if;
  return jsonb_build_object('users',(select count(*) from public.profiles),
    'notes',(select count(*) from public.notes where status='active'),
    'comments',(select count(*) from public.comments),'downloads',(select count(*) from public.download_logs));
end; $$;

-- Only the trusted Next.js server can write authentication events or check the login limiter.
create function public.login_is_locked(p_email text,p_ip inet default null) returns boolean language sql stable security definer set search_path = '' as $$
  select count(*) >= 5 from public.security_logs where action='LOGIN_FAILED'
    and created_at > now()-interval '15 minutes'
    and (username_attempt=lower(p_email) or (p_ip is not null and ip_address=p_ip));
$$;
create function public.record_auth_event(p_action text,p_email text,p_user_id uuid default null,p_ip inet default null)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if p_action not in ('LOGIN_SUCCESS','LOGIN_FAILED','ACCOUNT_LOCKOUT','LOGOUT') then raise exception 'Invalid action'; end if;
  insert into public.security_logs(user_id,username_attempt,action,ip_address)
    values(p_user_id,left(lower(p_email),100),p_action,p_ip);
end; $$;

-- Postgres grants EXECUTE to PUBLIC by default. Explicitly remove that default.
revoke all on all functions in schema private from public, anon, authenticated;
grant execute on function private.is_active(),private.is_admin() to anon, authenticated;
revoke all on function public.search_notes(text,integer,integer), public.search_notes_count(text,integer),
  public.create_note(text,text,text,text,text,integer,text,text), public.update_note(integer,text,text,text),
  public.remove_note(integer), public.add_comment(integer,text), public.remove_comment(integer),
  public.record_download(integer), public.set_user_status(uuid,text), public.admin_users(), public.my_stats(), public.admin_stats(),
  public.login_is_locked(text,inet), public.record_auth_event(text,text,uuid,inet) from public, anon, authenticated;
grant execute on function public.search_notes(text,integer,integer), public.search_notes_count(text,integer) to anon, authenticated;
grant execute on function public.create_note(text,text,text,text,text,integer,text,text), public.update_note(integer,text,text,text),
  public.remove_note(integer), public.add_comment(integer,text), public.remove_comment(integer),
  public.record_download(integer), public.set_user_status(uuid,text), public.admin_users(), public.my_stats(), public.admin_stats() to authenticated;
grant execute on function public.login_is_locked(text,inet), public.record_auth_event(text,text,uuid,inet) to service_role;

insert into public.subjects(subject_name) values ('Database and Web Security'),('Data Structures and Algorithms'),('Computer Networks'),('ภาษาไทยเพื่อการสื่อสาร');
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('notes','notes',false,10485760,array['application/pdf','application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-powerpoint',
  'application/vnd.openxmlformats-officedocument.presentationml.presentation','image/jpeg','image/png']);
-- Intentionally no storage.objects policies: user/anon keys cannot bypass the server's
-- file validation or download authorization. The service key stays server-only.
notify pgrst, 'reload schema';
commit;
